### ISSUE TITLE
Visuals

### ISSUE THREAD

**Issue by jlag34** [josegarban/colmar#3]
Visually, your page is a tad bit bland. You have some hover effects but not much styling. A little extra work into a color scheme would really make the page pop. Element wise, everything is in the right place and the layout is good.

**Comment by josegarban** [comment]
This time I wanted to focus on getting the divs doing what I wanted, but next time I will sure look for some inspirations in the resources suggested by Codecademy, such as Awwwards. Thanks for the input.
