### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [josegarban/colmar#4]
All in all, good job on this one. Your code itself looked good. I didn't find any errors and everything you entered in your files were good. Your media queries are on point. Nothing breaks their elements and they stayed aligned no matter the screen size. The only thing I would have liked to see from your project is a little more color to the page. Jazzing it up will make it look great on a resume. Keep up the good work!

**Comment by josegarban** [comment]
Thanks! I enjoyed the challenge.
